[build]
builder = "heroku/buildpacks:20"

[build.environment]
NODE_VERSION = "18"

[env]
CHROMEDRIVER_PATH = "/app/.chromedriver/bin/chromedriver"
GOOGLE_CHROME_BIN = "/app/.apt/usr/bin/google-chrome"
